### ISSUE TITLE
Voice autostarts when wifi switched off

### ISSUE THREAD

**Issue by johnno66** [PaulWoitaschek/Voice#1529] opened 2022-10-01 09:32 UTC
### What happened?

Since the current (6.1.2) version the app always starts automatically when I switch off wifi or when connection to current wifi network is lost.
Voice is normally not running in background (completely stopped via Developer options)

In the app permissions I've disabled Mobile data and Background data (so Voice is only allowed to use wifi data) but this does not alter this behavior.

Autostart of Voice is not wanted, correction would be appreciated.

Samsung Galaxy S9+  running /e/OS 1.4

### Version

6.1.2

**Comment by johnno66** [comment] 2022-10-10 09:07
Just upgrade to version 6.3.0 but unfortunately this behavior has not changed. Voice starts immediately after wifi is switched off

**Comment by theAkito** [comment] 2022-12-12 07:02
Seems like you have a very specific phone setup. This is probably the cause. Try making it more normal by disabling the developer options for this app & relieving the permissions. Do this step by step & note when it starts working properly, again.

**Comment by PaulWoitaschek** [comment] 2023-05-13 14:15
I'm closing this as a device specific edge case. Thanks for your report!

**Closed by PaulWoitaschek** 2023-05-13 14:15 UTC
