### ISSUE TITLE
[BUG] Notification Spam

### ISSUE THREAD

**Issue by Kardzhilov** [PaulWoitaschek/Voice#1069] opened 2021-07-12 20:19 UTC
When trying to play audio books it will spam audio notification "dings" every other second. So you hear one second of the audio book then a notification ding. 
This only happens when you are not in do not disturb mode. If you are in do not disturb mode it blocks the notifications so the audio books play uninterrupted. 

This has been an issue for me for over a year now i think but i expected that someone else would report it. 
I am running Android 11 (the issue was still there on Android 10 before i upgraded)
And my phone is an Asus Zenfone 6
I am running the latest version of the app available on the Playstore (April 2020).

**Comment by Kardzhilov** [comment] 2021-07-12 20:22
I see i actually reported this in November 2020 but it has been ignored https://github.com/PaulWoitaschek/Voice/issues/1033

**Comment by hackbot1337** [comment] 2021-07-20 17:35
have you done a complete clean install? remove the app and use something like sdmaid to remove and do a complete clean. reboot, reinstall, reboot and then only add one book as a test. i had other issues that seem to be caused by jank but doing a complete clean install solved many of my issues.

**Comment by PaulWoitaschek** [comment] 2022-08-26 21:25
This is a duplicate of https://github.com/PaulWoitaschek/Voice/issues/1255

**Closed by PaulWoitaschek** 2022-08-26 21:25 UTC
