### ISSUE TITLE
Persistent notification with no content

### ISSUE THREAD

**Issue by woodlander87** [PaulWoitaschek/Voice#828] opened 2019-01-06 22:02 UTC
Empty notification shows up when no content is playing and after the regular notification is dismissed. 

Empty notification cannot be dismissed.

App-Version: 4.1.2
Phone Name: OnePlus One
Android Version: Android 8.1 (Lineage OS 15.1)

**Comment by PaulWoitaschek** [comment] 2019-01-06 22:06
Can you post exact steps on how to reproduce this?

**Comment by woodlander87** [comment] 2019-01-06 22:14
I've tried to reproduce but have no set of steps that reproduces it consistently. After force stopping the application or restarting phone it goes away for a while and then reappears, even when the application hasn't been in the foreground since restarting.
I have a screenshot of what the notification looks like, but can't upload it on mobile. I'll upload it when I get to a desktop.
I have only seen this behavior since the UI redesign.

**Comment by woodlander87** [comment] 2019-01-07 15:55
![voice notification](https://user-images.githubusercontent.com/1791779/50777899-fd259a00-1259-11e9-8e51-8612fafec78d.png)

**Comment by woodlander87** [comment] 2019-01-22 17:23
Seems like it is probably related to the `createDummyNotification()` method on line 62 of `NotificationCreator.kt` and it's invocation on line 183 of `PlaybackService.kt`. Line numbers as of commit 81e5160a

**Comment by MadWalnut** [comment] 2020-03-07 14:15
I have the exact same issue. I can confirm the notification appears randomly even after force closing the app. The notification cannot be muted by Android system because it's of the type "Playback", which would also mute the normal playback notification. 

App version: 4.3.2
Phone name: OnePlus 6
Android version: 10

Is there a known workaround on the user side for now? It's a bit weird to have a Voice notification 24/7 that cannot be dismissed.

**Comment by PaulWoitaschek** [comment] 2020-03-07 14:21
Fixed in 5.x

**Closed by PaulWoitaschek** 2020-03-07 14:21 UTC
