### ISSUE TITLE
[Feature Request] Delete File

### ISSUE THREAD

**Issue by sengsational** [PaulWoitaschek/Voice#885] opened 2019-06-16 02:11 UTC
My personal use-case is to load podcasts into a directory on my phone from my PC (which has my podcast catcher).  

When I'm done listening, I want to delete the files as I go.

I've added a delete action (no code behind it yet).  Just wanted to see if there was a reason that, up to this point, file delete was not included.  Maybe it's a 'dumb idea'?  I like how this version puts files you've listened to already in a separate _Completed_ section, but if I'm going to "clean-up", I've had to go to a file-system app, and then I can't see which ones I've listened to already.

![DeleteAction](https://user-images.githubusercontent.com/15800701/59558201-92238080-8fba-11e9-9a49-813d518f883e.jpg)

**Comment by 0rAX0** [comment] 2019-06-24 13:52
I had to delete an audiobook as well and needed to go to the file manager to look for it. I'd love to see this as well! 👍

**Comment by markusd112** [comment] 2019-07-30 12:51
I think it is a good idea to implement a delete button. But not only for the whole book (folder with several MP3's), as well for single chapters (single MP3 files)

**Comment by sengsational** [comment] 2019-07-31 01:33
Yes, I was thinking that deleting single MP3 files would be in line with deleting podcasts that have been played.

**Comment by PaulWoitaschek** [comment] 2020-04-04 16:31
Duplicate of #554

**Closed by PaulWoitaschek** 2020-04-04 16:31 UTC
Labels: Feature Request
