### ISSUE TITLE
pause every two minutes

### ISSUE THREAD

**Issue by AlexanderKovalkov** [PaulWoitaschek/Voice#1532] opened 2022-10-02 06:54 UTC
### What happened?

 Hello, i use wireless headphones.  After the last update, playback is paused every two minutes.

### Version

6.1.2

**Comment by black-puppydog** [comment] 2022-12-03 09:37
Hi, ni habe the same problem but was on an older version than 6.1.2 (but can't remember which since I just cleverly updated without checking before...)
I'm on a Huawei p20 lite, in case that matters. My understanding is that Huawei is often exceedingly aggressive with their power saving "features"

**Comment by theAkito** [comment] 2022-12-12 06:52
Wireless headphones & frequent pauses indicate connection issues with the headphones.

**Comment by AlexanderKovalkov** [comment] 2022-12-12 07:24
> Wireless headphones & frequent pauses indicate connection issues with the headphones.

No, there are no problems with the headphones. There are no problems on other applications, for example, smart audiobooks

**Comment by theAkito** [comment] 2022-12-12 07:38
> No, there are no problems with the headphones.

The issue is connected to the headphones though, because without them the playback works fine.

Now, the question is, why the disconnects aren't interfering with the other apps.

**Comment by PaulWoitaschek** [comment] 2023-05-13 17:53
I assume that this is fixed with 7.0.11. If not, please report :)

**Closed by PaulWoitaschek** 2023-05-13 17:53 UTC
