### ISSUE TITLE
Feature request - Backup and restore option

### ISSUE THREAD

**Issue by W1zardK1ng** [PaulWoitaschek/Voice#2103] opened 2023-08-30 13:38 UTC
### Overview

Please add an option to export current app setting to a json file or something else and restore the book listen position and cover photo.

### How to reproduce

this will help to restore the app after a phone reset or app reinstall.

### Version

8.1.3

### Android Version

Android 13

### Device Model

Pixel 6a

**Comment by polyzen** [comment] 2023-08-30 19:59
Duplicate of https://github.com/PaulWoitaschek/Voice/discussions/1668

**Closed** 2023-09-03 09:15 UTC
