### ISSUE TITLE
Bug: Sleep timer doesn't work the second time.

### ISSUE THREAD

**Issue by bensonzachariah** [PaulWoitaschek/Voice#991] opened 2020-05-11 07:28 UTC
I've set the sleep timer to 5 mins and shake to reset.
It works fine the first time, audio begins to fade when the timer is about to end. I shake my phone and the timer resets.

However the playback isn't stopped the second time even if I can see the timer hit zero. I saw the timer hit zero and the sleep timer just stopped while the book was still playing.

Video proof of sleep timer not stopping playback: https://gfycat.com/keycrazyharpyeagle

Upon further testing I found out that if I shake to reset after the playback is completely stopped then the timer functions as normal.

However if I shake to reset during the audio fadeout and before the audio stops, the sleep timer fails to stop the playback as seen in the gif.

**Comment by Cheffu** [comment] 2020-06-22 09:56
I can confirm this bug. Before I read this issued, I did not know why I sometimes wake up and the audiobook is still playing, but this is the reason.

**Comment by facundoq** [comment] 2020-06-27 06:01
Same here, latest voice!

**Comment by nookits** [comment] 2020-09-29 10:54
I have experienced this. I thought it was intermittent but it may have been at times I was sharking after audio had stopped.

**Comment by PaulWoitaschek** [comment] 2022-02-14 22:24
This should be fixed in the latest beta
https://play.google.com/apps/testing/de.ph1b.audiobook

**Closed by PaulWoitaschek** 2022-02-14 22:24 UTC
