### ISSUE TITLE
When paused, play buttons disappear after short time

### ISSUE THREAD

**Issue by mefromthepast** [PaulWoitaschek/Voice#839] opened 2019-01-26 22:46 UTC
When I pause playback, the lockscreen widget and quicksetings entry disappear after some time, and obviously playback also does not resume when disconnecting headphones, waiting for some time and then re-connecting the headphones.
I am not sure if that may be related to battery management (is the process killed in background?), but then again other audio players just stay activated while Voice does not.

Thanks so much for this great software!

App-Version: 4.3.0
Android Version: Lineage 9.0

**Comment by littledrunkenman** [comment] 2019-02-20 07:47
I would suggest to either
1. Have the option to keep the app running or configure personalized shut down times
2. Get the option to configure voice as the main Music playing app, so it can be started by pressing the Headset button

Thank you so much for making this app!

**Comment by bagarwa** [comment] 2019-02-23 02:32
I have the same problem. Steps - 

1. Listening to an Audiobook on Voice. Screen is locked.
2. On the lockscreen, tap the pause button.
3. Within 5-60 seconds, the Voice notification vanishes. 

So I can't resume the playback from lockscreen anymore. I have to unlock the phone fully and switch to Voice app and press Play there to resume playback.

**Comment by Andrewskiz** [comment] 2019-03-11 05:48
Just chiming in to say I have the same issue. If the screen gets locked when playback is stopped, or if I take a call or use another app, the lockscreen player disappears and I have to unlock the device and open the app from recents to resume playback.

It would be great if the lockscreen / notification controls were more persistent, even if playback is stopped or another app is in the foreground. My music app, GoneMAD music player, does a great job of keeping the lockscreen player always active.

Thanks again for developing this amazing app.

**Comment by GangsterEmpire1** [comment] 2019-04-10 12:43
Any news on this, is there any fix? I have the same problem when pausing the audiobook the notification widget & lockscreen widget disappears after around 60 seconds. After that you can't resume the audiobook with a bluetooth headset. Then I have unlock phone and open the Voice app and press play.
I tried setting Voice battery management settings (Android) to manual so that the backround activity of the Voice app is not restricted but it didn't help.

Huawei phone
Android Version 9
App-Version: 4.3.2

**Comment by abguymon** [comment] 2019-05-28 20:16
Just wanted to add a +1 for this issue. Drives me nuts. If @PaulWoitaschek could point me in the right area I could take a look and see if I could do anything

**Comment by abguymon** [comment] 2019-05-28 20:17
#868 Is a duplicate of this issue

**Closed** 2019-05-28 21:05 UTC
