### ISSUE TITLE
Feature Request: Google Home capability

### ISSUE THREAD

**Issue by ErikLentz** [PaulWoitaschek/Voice#904] opened 2019-08-12 00:11 UTC
Feature Request: Sometimes I will want to finish an audiobook I was listening to in the car on my Google Home, but I can't seem to stream from Voice to the Google Home.

App-Version: 4.3.2
Phone Name: LG G7 ThinQ G710ULM
Android Version: 8.0

**Comment by NULLx76** [comment] 2019-10-06 15:53
As a workaround you can "cast screen to device" but native support would nicer.

**Comment by jtagcat** [comment] 2020-05-21 15:44
I would be careful with privacy.

**Comment by jtagcat** [comment] 2020-05-21 19:35
Duplicate of #76

**Comment by PaulWoitaschek** [comment] 2020-05-21 19:43
Thx

**Closed by PaulWoitaschek** 2020-05-21 19:43 UTC
Labels: Feature Request
