### ISSUE TITLE
Audiobook files are being deleted randomly

### ISSUE THREAD

**Issue by thw0rted** [PaulWoitaschek/Voice#1636] opened 2022-12-05 18:15 UTC
### Overview

I'm not able to reproduce this consistently, but my books are disappearing from my device.  I'd like some help with troubleshooting the problem.

For background, I have a `/Audiobooks` directory full of single-book m4b files, each in its own subdirectory.  Several months ago, books started disappearing from the device, and I thought I might have accidentally triggered some kind of "cleanup" function from Samsung.  I switched Voice to the beta channel in the Play store a few weeks ago, and books stopped disappearing for a while.  Last night, 3 of my books got deleted again.

I don't know if this is a Voice bug, or if I'm managing to trigger a (Voice) delete command accidentally somehow, or if it's not Voice's fault at all.  I was hoping maybe there would be an application log I can check or something to tell if Voice initiated deletion or not.

### How to reproduce

1. Play books as usual
2. Finished books, or books that have been reset to "not started", sometimes disappear from the device, but still appear in list within Voice.
3. Try to play book with missing file, play button turns to "pause" briefly then back to play, nothing else happens.

### Version

6.4.1

### Android Version

Android 12

### Device Model

Samsung A52s 5G

**Comment by thw0rted** [comment] 2023-03-20 03:18
This is still happening. A week or so ago, I downloaded the first dozen or so books in a series to the phone. We listen to each over the course of 2-4 nights. Twice in that week, I went to start a new book and found that the file was missing, and I had to download it again.  I still have no idea if Voice is somehow causing this, but I can't think what else it would be and I've never noticed any other files missing from the device.

**Comment by PaulWoitaschek** [comment] 2023-05-13 17:54
Duplicate of https://github.com/PaulWoitaschek/Voice/issues/1500

There is only one place where Voice deletes a book and I'm 99.999999% sure that this is not related to Voice.

**Closed by PaulWoitaschek** 2023-05-13 17:54 UTC

**Comment by thw0rted** [comment] 2023-05-14 03:34
Do you have any idea how I could come to have the book still listed in Voice, but the file is missing on disk? When this happens, the metadata is still there - cover art, title, I can even pick a chapter - I'm just unable to actually play it (because the file is gone).

Voice may not be deleting the file, but it's also not reacting to the file being removed the way it normally would, by removing it from the list. That's what gave me the idea that Voice could somehow be involved in the first place.

**Comment by PaulWoitaschek** [comment] 2023-05-14 04:09
That's very strange. Maybe it's a hardware failure?
What happens if your go to the voice settings and remove the audiobook folder, and go to the hook overview, and wait for the files to be removed?

You can add the folder late again and your current progress won't be lost

**Comment by thw0rted** [comment] 2023-05-14 14:09
The files are on internal storage, not an SD card, and I've seen no other signs of missing files elsewhere in storage or other buggy / strange behavior on this phone.  I'm not saying a hardware failure or broken OS installation is impossible, but it would be pretty weird if it were constrained to Audiobooks I play with Voice. (Obviously a bug like this in Voice, that nobody else encounters, would be equally weird!)

I believe I have removed and re-added the base book folder before, and the books with missing files do get removed from the Voice list. I can try again to confirm if that helps find a root cause.

**Comment by PaulWoitaschek** [comment] 2023-05-14 14:29
The only idea I have to diagnose this would be to capture a bug report as quickly as possible after the removal:
https://developer.android.com/studio/debug/bug-report

**Comment by thw0rted** [comment] 2023-05-15 03:00
The problem is I have no idea when the file disappears. Was it there until I hit the play button? Did it disappear an hour ago? Two days? If this was a PC I'd have a cron job run every minute and log the directory list so I could look back at it, but I don't think I can do that on a non rooted phone.
