### ISSUE TITLE
Over-persistent playback notification

### ISSUE THREAD

**Issue by Taylor-eOS** [PaulWoitaschek/Voice#1255] opened 2022-06-15 16:26 UTC
The playback control notification in the status bar is a bit over-persistent. It often opens when I play something with another app and then won't go away. I'm using the F-Droid variant. It's he same on different Android systems (I tried both Android 7 and 11).

**Comment by PaulWoitaschek** [comment] 2022-06-15 16:33
Which app version are you using?

**Comment by Taylor-eOS** [comment] 2022-06-15 16:39
The most recent one from F-Droid. It says 5.0.2.

On June 15, 2022 6:33:42 PM GMT+02:00, Paul Woitaschek ***@***.***> wrote:
>Which app version are you using?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulWoitaschek/Voice/issues/1255#issuecomment-1156689387
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- Sent from /e/ Mail.

**Comment by PaulWoitaschek** [comment] 2022-06-15 16:52
Can you check the beta? You can obtain it through play or through the github releases

**Comment by Taylor-eOS** [comment] 2022-06-15 18:24
Okay.
I only see alpha versions on github, none named "beta". Should I try the latest one of the alphas? It's from May.



On June 15, 2022 6:52:29 PM GMT+02:00, Paul Woitaschek ***@***.***> wrote:
>Can you check the beta? You can obtain it through play or through the
>github releases
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulWoitaschek/Voice/issues/1255#issuecomment-1156710020
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- Sent from /e/ Mail.

**Comment by Taylor-eOS** [comment] 2022-06-16 05:17
Little correction: The notification doesn't just open when I use another audio app, but seemingly randomly. (Playing audio just happenes to be what I use most of my screen time for.) I just had it open while browsing with Mull.


On June 15, 2022 10:25:38 PM GMT+02:00, ***@***.*** wrote:
>Screenshot is attached. The notification is "dead" in the sense that I
>can't press play on it and can't swipe it away. As mentioned it opens
>when another audio-playing app gets started. Skipping to the next track
>works and then the notification can be swiped away.
>
>
>
>On June 15, 2022 10:09:12 PM GMT+02:00, Paul Woitaschek
***@***.***> wrote:
>>Can you post a screenshot of the notification?
>>
>>-- 
>>Reply to this email directly or view it on GitHub:
>>https://github.com/PaulWoitaschek/Voice/issues/1255#issuecomment-1156883069
>>You are receiving this because you authored the thread.
>>
>>Message ID: ***@***.***>
>
>-- Sent from /e/ Mail.

-- Sent from /e/ Mail.

**Comment by PaulWoitaschek** [comment] 2022-06-16 08:05
Could you post a screenshot how the notification does look like?

**Comment by Taylor-eOS** [comment] 2022-06-16 11:56
I did send you a screenshot of the Voice notification a few emails ago in this thread
 Look for he attachment. If you meant something else, let me know.

AntennaPod now seems to randomly open notifications as well, so it might be a system issue. But that one is alive and I can swipe it away. (Which is odd, because this is the same system I've been using for years and it never did that.)

Thanks for your concern.

Best regards
Taylor



On June 16, 2022 10:05:30 AM GMT+02:00, Paul Woitaschek ***@***.***> wrote:
>Could you post a screenshot how the notification does look like?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulWoitaschek/Voice/issues/1255#issuecomment-1157360607
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- Sent from /e/ Mail.

**Comment by PaulWoitaschek** [comment] 2022-06-16 12:59
I think github ignores images you send by mail and that you need to attach it to the issue.

**Comment by Taylor-eOS** [comment] 2022-06-16 13:11
![Screenshot_20220616-150438](https://user-images.githubusercontent.com/78652522/174077118-b1014b48-29fa-44b7-b4c1-68b996d25a25.png)

**Comment by PaulWoitaschek** [comment] 2022-06-16 15:10
And this is with that 6.x alpha?

**Comment by Taylor-eOS** [comment] 2022-06-16 20:21
No, this is the F-Droid 5.x again. I went back because the notification behavior was the same and I didn't like the new UI.


On June 16, 2022 5:11:08 PM GMT+02:00, Paul Woitaschek ***@***.***> wrote:
>And this is with that 6.x alpha?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulWoitaschek/Voice/issues/1255#issuecomment-1157774309
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- Sent from /e/ Mail.

**Comment by Taylor-eOS** [comment] 2022-06-19 13:55
If you do find the cause of this bug, can you also release a 5.x version of the app with it fixed? I think I'll keep using 5.x, as the 6.x design doesn't fit very well with my Nougat OS. Everything since Oreo has become so plasticy.

-- Sent from /e/ Mail.

**Comment by PaulWoitaschek** [comment] 2022-08-26 21:25
This is a duplicate of https://github.com/PaulWoitaschek/Voice/issues/1255

**Comment by gwarser** [comment] 2022-08-27 06:55
@PaulWoitaschek This is #1255!

**Comment by Taylor-eOS** [comment] 2022-10-11 07:42
I'm sure it looks fine on a newer android system. But Nougat is generally very boxy and square. The 6.x alpha also wouldn't let me add single books, and I need too have my audiobooks in the podcasts folder so that the music player won't add the files to its library.



On June 16, 2022 10:21:15 PM GMT+02:00, ***@***.*** wrote:
>No, this is the F-Droid 5.x again. I went back because the notification
>behavior was the same and I didn't like the new UI.
>
>
>On June 16, 2022 5:11:08 PM GMT+02:00, Paul Woitaschek
***@***.***> wrote:
>>And this is with that 6.x alpha?
>>
>>-- 
>>Reply to this email directly or view it on GitHub:
>>https://github.com/PaulWoitaschek/Voice/issues/1255#issuecomment-1157774309
>>You are receiving this because you authored the thread.
>>
>>Message ID: ***@***.***>
>
>-- Sent from /e/ Mail.

-- Sent from /e/ Mail.

**Comment by PaulWoitaschek** [comment] 2022-10-11 08:11
What about 6.3?

**Comment by Taylor-eOS** [comment] 2022-10-11 10:24
It works fine both on 6.1.1 and what the current version on F-Droid is (I can't check, because the Menu won't let me scroll, so I can't see the App version).

**Comment by Taylor-eOS** [comment] 2022-10-15 17:01
The Over-persistent playback notification problem is gone in 6.3 too.

On 11 October 2022 12.24.23 CEST, Taylor ***@***.***> wrote:
>It works fine both on 6.1.1 and what the current version on F-Droid is (I can't check, because the Menu won't let me scroll, so I can't see the App version).
>
>
>On October 11, 2022 10:12:00 AM GMT+02:00, Paul Woitaschek ***@***.***> wrote:
>>What about 6.3?
>>
>>-- 
>>Reply to this email directly or view it on GitHub:
>>https://github.com/PaulWoitaschek/Voice/issues/1255#issuecomment-1274277534
>>You are receiving this because you authored the thread.
>>
>>Message ID: ***@***.***>
-- Sent from /e/ Mail.

**Closed** 2022-10-17 04:05 UTC
