### ISSUE TITLE
[BUG] Bluetooth issues in Android 10

### ISSUE THREAD

**Issue by Kardzhilov** [PaulWoitaschek/Voice#931] opened 2019-11-22 23:29 UTC
When you have a bluetooth headset connected it will automatically bring up the player in the notification. If you dismiss it after some time the notification in the attached image appears. It can not be dismissed, the only way to remove it is to force close the app.
![image](https://user-images.githubusercontent.com/15326512/69467386-f75c7880-0d87-11ea-99f2-3eb7a0297048.png)

None of these things were happening before updating to android 10.

App-Version:4.3.2
Phone Name:Zenfone 6
Android Version:10

**Comment by PaulWoitaschek** [comment] 2020-01-31 22:41
This is a duplicate of #915

**Closed by PaulWoitaschek** 2020-01-31 22:41 UTC
