### ISSUE TITLE
[Feature request] Integrate with Google Drive

### ISSUE THREAD

**Issue by chrisvaneijk** [PaulWoitaschek/Voice#924] opened 2019-10-24 08:15 UTC
As a user I want to be able to add Google Drive folder, so I can play my audiobook directly from Google Drive

**Comment by evra** [comment] 2019-11-06 22:01
Having this feature can also enable easy Integration with chromecast.

**Comment by innesst** [comment] 2019-11-07 07:34
"easy" 😂

**Comment by brianredbeard** [comment] 2019-11-27 00:40
Duplicate of:
 - #229
 - #855 
 - #884

**Comment by bthoem** [comment] 2020-03-17 12:32
This would be a wonderful feature - to be able to stream my audiobooks directly from Google Drive, with synchronization of reading position. Tx.

**Comment by Shadesss** [comment] 2020-06-30 23:35
This would be amazing!

**Closed as completed** 2022-08-06 09:41 UTC
