### ISSUE TITLE
[BUG] Audiobook Display doesn't Change in an Audiobook Directory

### ISSUE THREAD

**Issue by DMNinja** [PaulWoitaschek/Voice#1049] opened 2021-02-22 17:48 UTC
**Is your feature request related to a problem? Please describe.**
When i import a folder of serialized audiobooks (each with their own cover art), the app treats the cover art of the first book as the cover art for the whole folder. To circumvent that, i need to drop every individual file within the directory, making a mess of my collection (when viewed through a file explorer). Especially when i try to add/remove books inside the main directory

**Describe the solution you'd like**
I'd be nice for the app to be able to pull the cover art for each book individually

**Describe alternatives you've considered**
No idea how to go about this in any other way

**Additional context**
The way the app is set up, this is not an issue encountered when playing a music album for example, but it would greatly benefit listeners of serialized publications (like Big Finish Audio)

**Comment by carsten-engelke** [comment] 2022-01-30 21:15
This is an issue for me as well.

**Comment by DMNinja** [comment] 2022-12-31 16:58
Sorry for bumping this, but is it too much to ask for a status update on the OP?

**Comment by PaulWoitaschek** [comment] 2023-05-13 17:49
Thanks for the report. This is actually a duplicate of #1643. Well, technically #1643 is a duplicate of this.
I gave an explanation in that ticket.

**Closed by PaulWoitaschek** 2023-05-13 17:49 UTC
