### ISSUE TITLE
Cover image not showing on some books

### ISSUE THREAD

**Issue by JKleinHub** [PaulWoitaschek/Voice#811] opened 2018-12-28 11:27 UTC
I have a number of books on my phone. Each of them has a single 'cover.jpg' in its folder, which gets displayed for all of the books expect for two. I tried multiple things, but cannot figure out, why the cover is not showing. Every other media player I tried correctly displays all the cover images.

I suspect it is either a bug in the cover image handling, or Voice uses some strange rules to determine which image should be shown as cover art.

I am using version 3.6.1 from the F-Droid store on a LG G6 phone with Android 8.0.0.

I'm unsure what more information to provide, I can't exactly upload my whole audio book collection to make it reproducible...

**Comment by 4ut0-M-4t** [comment] 2019-01-02 16:07
In my experience, it's some sort of intentional cover size restriction. Just make sure that all your book covers are less than 300-350kB and the problem goes away.
@PaulWoitaschek would resolve this issue best.

**Comment by Riotous** [comment] 2019-01-06 08:05
@4ut0-M-4t then we need some documentation as to what limitations there actually are.

**Comment by JKleinHub** [comment] 2019-01-06 10:40
I don't like the concept of silent failing. If a user puts a cover picture into the folder, he expects it to be shown. If it can't, then there should be a hint to why it could not. Not necessarily a popup message, but maybe a Log file accessible through the menu, or maybe something could be printed on the replacement image (where usually only the first letter is shown). It is just extremely frustrating to think, that I spend about 20 minutes (and did not succeed) on the problem, when somewhere there is an extremely simple reason, why the image is not shown, and with its knowledge, I could have fixed the problem in 2 minutes.

Also, maybe a size restriction can be removed. I understand, that potentially theses cover images are read many times and big files would slow down the program, but maybe this could be avoided through more clever caching algorithms or whatever.

**Comment by 4ut0-M-4t** [comment] 2019-01-24 19:51
@Riotous, as I've already mentioned, @PaulWoitaschek knows best and it's not my place to comment, but the problem is apparently linked to [Picasso](https://github.com/square/picasso) image loading/caching library.

**Comment by Riotous** [comment] 2019-01-24 21:04
@4ut0-M-4t Then maybe it's time for @PaulWoitaschek to switch to Glide instead of Picasso?

**Comment by kanjieater** [comment] 2019-08-24 19:11
Does the image have to be embedded into all of the files or should just an image in the folder be picked up as well? Still dealing with this issue.

**Comment by nyahwhy** [comment] 2020-02-14 07:01
I have the same problem. It appears to be the length of the full path for the cover image that is the main problem / in my case it was not related to the content of the files.

Shortening only the name of the cover image doesn't help most of the time, I need to rename the directory so it's re-indexed I think? Shortening both directory and cover filename fixed the problem most of the time. I renamed them on my PC and synced them, which means I don't know if deletion / recreation is necessary for the process to work or if you can rename them right on the phone.

Note that the covers that were broken were NOT the ones with the longest paths - it was mixed (there were working covers with longer paths), but shortening paths fixed the covers anyways and making them longer broke them. So, there is something else involved. Wasn't able to figure out what. Looks like the application is somehow tracking audio books even if they are renamed (some of the time) and the error can get stuck as long at it is recognized as the same audio book? And possibly it's something related to the length of the file name of the first audio file? Or the length of the title? Or all of the above? Tired of renaming / copying / moving stuff around. It's probably witchcraft or something. Good luck.

**Comment by nyahwhy** [comment] 2020-05-22 06:18
Just noticed that shortening the displayed book name (as in: long press book / [T] Name) of a book is enough to work around this issue. Adding a cover works after name is shortened.

**Comment by ggogel** [comment] 2021-03-03 01:07
I have the same issue. On some books it is not picking up the image in the folder neither can I set an image manually. I've got no idea why.

**Comment by nyahwhy** [comment] 2021-03-03 13:55
I haven't encountered this bug since I switched to a new phone, so the main suspect for this bug is probably related to something I got rid of, most prominently: 
- I had my audio books stored on a removable sd card ext4 (now have my audio book folder on internal). 
- Also I switched from android 9 (?) to 10 (?) I think (lineage 16 to 17.1)

**Comment by ggogel** [comment] 2021-03-03 14:08
After I changed the folder name from `Corey, James S. A. - The Expanse 2.5 - Gods of Risk - An Expanse Novella` to
`Corey, James S. A. - The Expanse 2.5 - Gods of Risk` the cover worked. So the path was either too long or contained too many dashes. Only changing the name withing the app didn't help.

**Comment by PaulWoitaschek** [comment] 2022-08-30 21:29
I assume this is fixed in Version 6+.

**Closed by PaulWoitaschek** 2022-08-30 21:29 UTC
