### ISSUE TITLE
[Feature Request] Delete file option

### ISSUE THREAD

**Issue by felixlang** [PaulWoitaschek/Voice#736] opened 2018-06-25 11:09 UTC
Nice application. I use it to listen to podcasts instead of audiobooks, because it's the only FOSS audio player I'm aware of that explicitly saves the last position of the file, which is important since most of the podcasts I listen to are an hour or longer.

With that in mind, one feature that would be helpful is the ability to delete the files from the phone, once I am done listening to them. Since I usually have multiple podcasts from the same source on my phone at one time, they all share the same cover image and title when displayed in Voice. And that makes it hard to keep track of which ones I've finished with.

App-Version: 3.6.1
Phone Name: Nokia 6.1
Android Version: 8.1.0

**Comment by PaulWoitaschek** [comment] 2018-06-25 11:55
Did you try antennapod?

**Comment by felixlang** [comment] 2018-06-25 13:50
Yes, just before Voice actually. AntennaPod would work for many of the podcasts I listen to, however it cannot be used to simply play mp3 files that are already on the phone. So it's an incomplete solution (audio from the Supreme Court is an example).

**Comment by Riotous** [comment] 2019-01-06 08:03
I would also like a delete function because audiobooks can take up a lot of space and deleting them on the fly is a quick way to make room for more.

**Comment by innesst** [comment] 2019-01-06 17:32
While I would also like to be able to delete from within the app (maybe accessible by long pressing on the book cover), I listen to podcasts by putting them all in a sub folder, and then each episode is a chapter.

**Comment by thw0rted** [comment] 2019-01-31 22:13
Duplicate of #554. Cc @PaulWoitaschek

**Comment by PaulWoitaschek** [comment] 2020-04-04 16:31
Thanks @thw0rted

**Closed by PaulWoitaschek** 2020-04-04 16:31 UTC
Labels: Feature Request
