### ISSUE TITLE
App auto starting with bluetooth

### ISSUE THREAD

**Issue by W1zardK1ng** [PaulWoitaschek/Voice#2008] opened 2023-06-26 05:32 UTC
### Overview

even if i Force Stop the app, when i turn on Bluetooth (without even connecting to a device) the app is starting and showing the current playing item in the media control area. This is very annoying since i have to force stop the app every time i turn on the bluetooth but i don't want the media controls there. 

Please fix this issue.

### How to reproduce

Force stop the app
turn on bluetooth

the app will auto start

### Version

8.1.0 

### Android Version

Android 13

### Device Model

Pixel 6a

**Comment by polyzen** [comment] 2023-06-28 22:00
Duplicate of #1991 I think

**Comment by polyzen** [comment] 2023-06-28 22:01
> Thanks for reporting this longstanding issue.
> 
> I've the same problem since ages.

This had actually been resolved, but I think it came back when #1958 was fixed.

**Comment by PaulWoitaschek** [comment] 2023-07-01 10:49
Yes, that is correct.

Can you please try this release and report back if it fixes your issue?

https://github.com/PaulWoitaschek/Voice/releases/tag/8.1.1

**Comment by W1zardK1ng** [comment] 2023-07-01 15:37
Looks like the app auto opening issue is resolved, Thanks a lot.

However after playing a media and pausing it, the media control option is still staying even after the app is closed from recent app, the only was to remove it is to force close this app from settings. Not sure if this is how it is designed for Voice app. For other apps i use the media control used to go away if i close the app from recent apps.

**Comment by PaulWoitaschek** [comment] 2023-07-01 16:10
IMO that's the correct behavior for Apps targeting Android 13. If I understand it correctly you have enabled "Pin Mediaplayer". If you don't want that behavior you can disable it (long click on the notification, then in the top right on the gear icon)
It's the same behavior as for instance PocketCasts.

Thanks for your report!

**Comment by PaulWoitaschek** [comment] 2023-07-01 16:11
For the reference, this was the fix https://github.com/PaulWoitaschek/Voice/pull/2012

**Closed by PaulWoitaschek** 2023-07-01 16:10 UTC

**Comment by landry314** [comment] 2023-07-03 09:31
thank god. i had to disable the app.
