### ISSUE TITLE
Lock screen images are ugly

### ISSUE THREAD

**Issue by larsey** [PaulWoitaschek/Voice#486] opened 2016-09-14 19:32 UTC
Can we please have a setting that turns off that feature? So the app does not replace the lock screen background?

**Comment by PaulWoitaschek** [comment] 2016-09-15 04:58
What's ugly about them?

There won't be a setting for such a minor thing.

**Comment by larsey** [comment] 2016-09-15 06:41
They are ugly because not all audio books comes with a image, that is used to set the lock screen image, that is high quality and made for that purpose.

I have a couple of audio books and it seems to be a 100x100 thumbnail stretched out to my phone 1920 x 1080 resolution. Hopefully you may think how bad it looks!

It should not be a big deal to implement? Just add a ui switch that controls wherever it should set the lock screen. Surly it cant be more than a couple lines of code since you already are doing this.

**Comment by PaulWoitaschek** [comment] 2016-09-15 11:30
My first design principle is minimalism. So no setting / UI component that I don't think is absolutely necessary will reach the app.

But it's a good point. I'll check the quality of an image and simply set the default cover if it's too bad.

**Comment by nioncode** [comment] 2017-01-02 16:24
I would also prefer to completely disable cover art on the lock screen.

**Comment by MrReSc** [comment] 2017-03-15 18:11
I completly agree with larsey. The thumbnail on a HiDPI screen looking very ugly.
You should simply disable the cover art on the lockscreen.

**Comment by sandybeachit** [comment] 2017-06-08 22:04
Is this a duplicate of # 581 and if so can we close it off ?

**Comment by gwarser** [comment] 2017-06-09 08:53
Form me it is a problem with lock screen control buttons - they are barely visible on some cover art images.

**Comment by PaulWoitaschek** [comment] 2017-06-09 09:02
Can you upload a screenshot where it's barely visible?

**Comment by sandybeachit** [comment] 2017-06-09 09:44
It could be the cover art is making navigation difficult? But without a 
screenshot I'm just guessing, could you upload a screenshot please.

**Comment by MrReSc** [comment] 2017-06-09 10:18
For me, it's just an optical thing. I nerver had an issue with the control buttons. It just looks ugly in case of low resolution cover art. I would prefer a Preference for toggling cover art on lockscreen.

**Comment by gwarser** [comment] 2017-06-09 13:29
> Can you upload a screenshot where it's barely visible?
I cannot take screenshot of lock screen. 
Anyway, probably this cannot be seen on screenshot - it's subjective, not only about color, but also about stripes and edges, and bright sun :)
I may try to take photo.

**Comment by gwarser** [comment] 2017-06-09 13:39
Photos taken i dark room, so they are not 100% representative
Even default MAP background can be problematic:
![2017-06-09_151647_1](https://user-images.githubusercontent.com/886325/26977565-a30872b0-4d28-11e7-8520-97c3b2ffb35c.jpg)
Not looks so bad for buttons, but title is not visible:
![2017-06-09_152550_1](https://user-images.githubusercontent.com/886325/26977636-e3086aa0-4d28-11e7-9405-de1b7bcb86fb.jpg)
I often have problem with missing navigation buttons, and here I just don't know, are they missing or not visible?
![2017-06-09_152647_1](https://user-images.githubusercontent.com/886325/26977677-074f34de-4d29-11e7-88bd-dd8003d897ed.jpg)

Also I just discovered, if I select cover from Internet, I must change book to another, play for moment and then change back, to force update in lock screen and android status area/widget.

**Comment by sandybeachit** [comment] 2017-06-09 15:48
Ok so correct me if i am wrong, but the issue i see is the white text from
Material Player merging into the image on the lock screen ?

I can see a possible solution, so in the screenshot below in the yellow box
the back, forward and pause buttons are white but with a black edging, the
text in the red box does not have any black edging around the edge of the
text or the logo which makes it fade into the background image.

Paul how about if we add black edging to all the text that appears on the
lock screen and not just for the back, forward and pause/play buttons. Is
this possible ?

[image: Inline images 1]

Thank You

David Beach





All Linked Connection requests will be accepted

You do not have permission to add this email address, my name, details or
any information contained within this email to any of your mailing, sales,
marketing or any other mailing lists without my written consent.

You do not have permission to pass or sell on this email address, my name,
details or any information contained within this email to any individual or
organization or third parties regardless without my written consent.

Failure to adhere to this illegal under UK and EU law and constitutes
illegal spam emails, phone calls or letters etc and will be reported to the
relevant governmental or regulatory body.

**Comment by PaulWoitaschek** [comment] 2017-06-09 16:20
No, that's completely not under my control. Also this only happens on really old Anroid versions I don't want to put additional focus on.

From Lollipop on it looks like this:
![screenshot_20170609-181801](https://user-images.githubusercontent.com/743462/26984590-3f04cddc-4d40-11e7-9332-866660fdce4d.png)

**Comment by nioncode** [comment] 2017-06-09 16:26
Maybe you might want to rethink merging #581, where I added a simple preference for toggling the cover art on the lockscreen?

**Comment by sandybeachit** [comment] 2017-06-11 15:52
What about dimming the lock screen art so it is always slightly darker than the lock screen text, is this possible ?

**Comment by PaulWoitaschek** [comment] 2017-06-11 16:09
It gets dimmed on Lollipop and later automatically.

**Comment by sandybeachit** [comment] 2017-06-11 16:47
Ah i never noticed, so is this really a problem then ? Or just an issue of
low quality artwork which would be outside of Material Players control ?

Thank You

David Beach





All Linked Connection requests will be accepted

You do not have permission to add this email address, my name, details or
any information contained within this email to any of your mailing, sales,
marketing or any other mailing lists without my written consent.

You do not have permission to pass or sell on this email address, my name,
details or any information contained within this email to any individual or
organization or third parties regardless without my written consent.

Failure to adhere to this illegal under UK and EU law and constitutes
illegal spam emails, phone calls or letters etc and will be reported to the
relevant governmental or regulatory body.

**Comment by docsav** [comment] 2017-11-30 06:58
I am commenting on this issue due to the volume of discussion that has occurred here already, and because it is open, even though 581 is probably the more specifically topic.

I understand that conceptually, adding another setting for this violates the concept of clean design and simplicity. I think that might be the wrong way to look at the problem though. Realistically, the root problem is that the app hijacks the existing lockscreen graphics on a user's device by default. You mention that if the user doesn't like the cover art that came with the book, they should use the tool in the app to search and set a more preferable cover. That means if a user isn't happy with a significant change to their device preferences, the alternative is to go through their local collection, and reassign more appealing covers to each book, or assign a new cover to a new book each time the user starts one. That is a way more complex design choice and a heavier burden on users than adding another preferences toggle. 

The stated first design principle is minimalism, and I don't think anything about placing an image other than what a user chooses on one of the 2-3 interfaces that users see most often in Android promotes minimalistic design. Remember that minimalism isn't a function of visual aspects alone, it is about the user experience as well.

I haven't had a problem with controls being hard to see or really bad low-res cover images. I just don't want to see cover images when I unlock. As a user experience geek, I pick my lockscreen images with care. Each book cover is picked by some committee working for a publisher, promoting their aesthetic and marketing agendas. If we're lucky, the author, whose work I use Voice to experience _might_ get some input, if he is successful enough (or cares enough) to be influential. If my preference is to use Voice and not deal with that, then I must manually curate a different cover for each book.

I really enjoy most other aspects of the player. Hoping I can provide a bit of a different perspective on this. Thanks!

**Comment by joshunger** [comment] 2018-11-15 17:16
Is it possible to automatically download a higher resolution image?

**Comment by joshunger** [comment] 2018-11-16 23:22
I noticed that https://www.overdrive.com/ includes a 9 9× 132 image on most audiobooks. I wonder if this could be improved?

**Comment by PaulWoitaschek** [comment] 2019-03-21 09:08
Android Q blurs the lockscreen - problem solved :)

**Closed by PaulWoitaschek** 2019-03-21 09:08 UTC
Labels: PR Welcome
