### ISSUE TITLE
v7 no longer works with a volume-button - skip-track - app

### ISSUE THREAD

**Issue by metbic** [PaulWoitaschek/Voice#1730] opened 2023-03-20 20:27 UTC
### Overview

So I happen to use an app called "frinky music controller" to skip tracks with the volume keys when the screen is off. This app has been a wonderful team with Voice for many years. However since version 7.0.0 it no longer works. Sorry if this is too awkward to fix.

### How to reproduce

Install the ancient app "frinky music controller"
Use Voice 6.5 or earlier 
Switch off the screen
Skip track or ffwd with volume button
Update to Voice 7.0.0
Switch off the screen
Volume buttons no longer respond like they did

### Version

7.0.0 (fdroid)

### Android Version

13

### Device Model

Pixel 4a

**Comment by PaulWoitaschek** [comment] 2023-03-20 21:02
What exactly is Voice 7 referring to? Does it reproduce with 7.0.3?

**Comment by PaulWoitaschek** [comment] 2023-03-20 21:55
You can install the latest release from Github (you need to uninstall the fdroid version first)
https://github.com/PaulWoitaschek/Voice/releases/tag/7.0.3

This is very likely a dupe of #1710

**Closed by PaulWoitaschek** 2023-03-20 21:55 UTC
