### ISSUE TITLE
id3 tag version (or encoding)

### ISSUE THREAD

**Issue by radlerandi** [PaulWoitaschek/Voice#858] opened 2019-03-19 21:23 UTC
just to want to let you know:
i use voice to listen various podcasts, because it's the only tool so far i found which saves the last playing position when the app closes. 
Because i sometimes also listen to the same files on my old mp3 player i update all of the mp3 ID3 tags with the program Mp3tag.
Some of the updated files won't play with Voice, some do. I had no clue why but today i investigated.

Downloaded some original podcast files, updated Mp3tag program, saved again, no change. 

Then i changed the ID3 version and switched from ID3 v2.4 UTF-8 to ID3 v2.3 UTF-16 and suddenly all files can be played. 

I guess it was not a Umlaut/special character problem because one of the not playing files had no such characters in ID3, see https://imgur.com/a/QHGqlny

So, i solved my problem, and perhaps others can use this as a workaround - in case this is a "won't fix". ;-)

anyway, thanks for this program, keep up the good work :-)

**Comment by PaulWoitaschek** [comment] 2019-03-20 05:54
Can you send me such a file twice? Once where it works and once where it doesn't?




--


Mit freundlichen Grüßen


Paul Woitaschek







On Tue, Mar 19, 2019 at 10:23 PM +0100, "radlerandi" <notifications@github.com> wrote:












just to want to let you know:

i use voice to listen various podcasts, because it's the only tool so far i found which saves the last playing position when the app closes.

Because i sometimes also listen to the same files on my old mp3 player i update all of the mp3 ID3 tags with the program Mp3tag.

Some of the updated files won't play with Voice, some do. I had no clue why but today i investigated.


Downloaded some original podcast files, updated Mp3tag program, saved again, no change.


Then i changed the ID3 version and switched from ID3 v2.4 UTF-8 to ID3 v2.3 UTF-16 and suddenly all files can be played.


I guess it was not a Umlaut/special character problem because one of the not playing files had no such characters in ID3, see https://imgur.com/a/QHGqlny


So, i solved my problem, and perhaps others can use this as a workaround - in case this is a "won't fix". ;-)


anyway, also thanks to this programm, keep up the good work :-)

**Comment by radlerandi** [comment] 2019-03-20 20:41
I did some testing and found a small file which curiously works with id3 v2.4 and the above mentioned file that does not work with id3 v2.4. I have no idea why the small files works ...
https://drive.google.com/open?id=1b_PSabud_k9zzncwJtCGOhBY-EXngF_E
An existing id3 v1 tag does not matter, so i removed it.

**Comment by PaulWoitaschek** [comment] 2019-03-26 08:45
@radlerandi 
Little heads up: It seems there is a bug in Mp3Tag causing it to write defect metadata.
I also reached out to the author of Mp3Tag. For more details follow the linked issue.

**Comment by fheidenreich** [comment] 2019-04-02 07:40
Just to clarify, the issue was caused by ExoPlayer not removing ID3v2.4 unsynchronization correctly. I've pointed out the bug in the linked issue which is now fixed in the current dev branch.

**Comment by radlerandi** [comment] 2019-04-05 17:40
Great! Thank you for your efforts and responses.

**Closed** 2022-08-26 21:38 UTC
