### ISSUE TITLE
Playback time inaccuracy

### ISSUE THREAD

**Issue by TheSleevePSU** [PaulWoitaschek/Voice#1055] opened 2021-03-27 23:35 UTC
On long audio files, the displayed elapsed playback time-keeping seems to be inaccurate, so that it slowly "drifts" from the actual elapsed time. For example, if I play a file for 20 minutes, the elapsed time actually progresses 21 minutes instead of 20. This means that upon exiting the app and coming back, playback resumes from 1 minute later than expected, meaning a large chunk of audio is skipped.

This is easy to see at the end of playback when you finish a file, and the elapsed time displayed is a larger number than the total length of the file, as in the attached screenshot.

![Screenshot_20210327-161855](https://user-images.githubusercontent.com/13119592/112737811-6d439780-8f1a-11eb-9084-e53a776661c4.png)

**Comment by ueen** [comment] 2021-04-11 19:20
This might be an issue with the file, i know there was a but in FFmpeg some time ago.
In can be fixed with foobar2000 right click on file and select Utilities>Fix VBR MP3 Header

**Comment by afferenslucem** [comment] 2021-04-15 03:18
I have same issue many times.
App shows file length is 20:17, but I listen 44:34 and playing is interrupted at middle of word.
Fortunately I listen that book second time.

**Comment by afferenslucem** [comment] 2021-04-15 03:34
> This might be an issue with the file, i know there was a but in FFmpeg some time ago.
> In can be fixed with foobar2000 right click on file and select Utilities>Fix VBR MP3 Header

Yeah, this is fix trouble, but maybe should integrate it in app?
To fix headers when I add books. Now I download book from internet directly to phone. I don't wanna move to computer, fix headers and move it to phone

**Comment by TheSleevePSU** [comment] 2021-04-16 17:46
I am experiencing this on mp3 files with CBR encoding, so I don't think it has anything to do with VBR headers. I will try this weekend to take notes on detailed reproduction steps and then will post them here.

**Comment by TheSleevePSU** [comment] 2021-04-16 21:29
Just confirmed while listening in the car. I paused audio for about 30 seconds while I was order food at a drive through restaurant. When I hit the play button to resume, audio had jumped forward by about 2 or 3 minutes, so I hat to hit the rewind button 6 or 7 times to get back to where I was previously.

Audio file is CBR mp3 at 128 kbps, stereo encoding, about 8 hours in length. Unfortunately I want able to capture detailed repro steps because I was in the car. Will try to repro again in the next few days.

**Comment by mariohock** [comment] 2022-10-03 09:47
I have the same issue; mp3val shows: "921939 MPEG frames (MPEG 1 Layer III), no tags, CBR"

The file is an audiobook and contains about 6h of audio at 80kbit/s.

**Comment by ueen** [comment] 2022-10-03 12:20
> This might be an issue with the file, i know there was a but in FFmpeg some time ago. In can be fixed with foobar2000 right click on file and select Utilities>Fix VBR MP3 Header

@mariohoch try to fix the file, that's most likely the cause

**Comment by PaulWoitaschek** [comment] 2023-05-13 17:45
Thanks for the report.

Thats unfortunatelly a limitation right now and there is nothing we can do about. However, once ExoPlayer supports this better, Voice will get that behavior too.

https://github.com/google/ExoPlayer/issues/9408

For now I can only recommend to convert your files to a more modern format like m4b / aac

**Closed by PaulWoitaschek** 2023-05-13 17:45 UTC
