### ISSUE TITLE
Constant audio notifications while playback

### ISSUE THREAD

**Issue by chidniu** [PaulWoitaschek/Voice#1433] opened 2022-08-10 12:11 UTC
### What happened?

Since updating from 5.0.2 to 6.0.7 the app sends constant notifications while playback (approximately every two seconds). So there is a bit of playback then it is interrupted (the generic notifications sound is played, no visible notification though) and then the playback resumes. This then just repeats and makes the app unusable. 

If I set the phone to silent it instead vibrates consistently every two seconds.

I've installed Voice from F-Droid and my phone is a Motorola One Vision (XT1970-3) with Android 11.

### Version

6.0.7

**Comment by PaulWoitaschek** [comment] 2022-08-26 21:32
This is a duplicate of https://github.com/PaulWoitaschek/Voice/issues/1255 and should be fixed in 6.0.10.

**Closed by PaulWoitaschek** 2022-08-26 21:32 UTC
