### ISSUE TITLE
Delete files from app?

### ISSUE THREAD

**Issue by HikaruGunner** [PaulWoitaschek/Voice#932] opened 2019-11-27 12:54 UTC
Is there a way to delete audio files directly from the app?

Best regards

**Comment by kalbidad** [comment] 2019-12-30 15:15
Would really like to see this feature implemented. Hope it's in the pipeline!

**Comment by PaulWoitaschek** [comment] 2020-04-04 16:31
Duplicate of #554

**Closed by PaulWoitaschek** 2020-04-04 16:31 UTC
