### ISSUE TITLE
"Continue to play" on Android 14 not working

### ISSUE THREAD

**Issue by Nvethrandil** [PaulWoitaschek/Voice#2229] opened 2023-12-18 17:58 UTC
### Overview

Resuming play utilizing the active-media section of the top-menunon Android 14, after swiping the app away, does not trigger anything. 

Nothing crucial but interesting that it does not get relaunched by that action.

### How to reproduce

1. Open app
2. Play book
3. Swipe away app / close app
4. Press play via the media menu of the Android top-screen menu
5. Does nothing.

### Version

8.1.3

### Android Version

34

### Device Model

Pixel 6

**Comment by PaulWoitaschek** [comment] 2024-01-19 12:14
Thanks for reporting, closing as a duplicate of https://github.com/PaulWoitaschek/Voice/issues/2110

**Closed by PaulWoitaschek** 2024-01-19 12:14 UTC
