### ISSUE TITLE
Issue: Voice keeps crashing after audiobook finishes

### ISSUE THREAD

**Issue by 85pando** [PaulWoitaschek/Voice#1013] opened 2020-08-09 10:38 UTC
**Describe the bug**
After finishing Audiobook, Voice crashes on trying to open it.

**To Reproduce**
1. Finish any audiobook with Voice in the background (single file book or folder).
2. After finish, try to open Voice.
3. Crash continuously

**Expected behavior**
Voice should open into the menu, enabling you to select a new audiobook.

**Screenshots**
n/a

**Smartphone**
 - Device: OneNote 6
 - Android Version: Android 10
 - Voice Version 5.0.2 (F-Droid)

**Additional context**
- It seems not to be connected to any specific audiobook, have retried with multiple books afterwards.
- The only fix at the moment seems to be to clear all storage, basically resetting the app. Clearing cache does not suffice.

PS: The issue template is not selectable in GitHub Issues.

**Comment by ix5** [comment] 2020-08-12 14:32
Most likely a duplicate of https://github.com/PaulWoitaschek/Voice/issues/995, or at least related.

Well, as for a temporary workaround, you might try moving the mp3 file of the currently playing audiobook - that should trigger a re-loading of the file and reset play state.

**Comment by PaulWoitaschek** [comment] 2023-05-13 14:02
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.

**Closed by PaulWoitaschek** 2023-05-13 14:02 UTC
