### ISSUE TITLE
No chapters

### ISSUE THREAD

**Issue by strider72** [PaulWoitaschek/Voice#1448] opened 2022-08-15 05:54 UTC
### What happened?

As of version 6, the book I'm listening to no longer shows chapters. No display of current chapter, and no ability to go immediately to a chapter.  Huge loss to the UI

### Version

6

**Comment by PaulWoitaschek** [comment] 2022-08-15 07:48
How did you set up your folder structure?
Does it fullow the pattern described in the explanation card?

> Voice expects a folder structure where every folder within your selected audiobook folder is one book

What version are you using? There is no version 6.

**Comment by strider72** [comment] 2022-08-16 12:11
Latest version in F-Droid: 6.0.7

Okay, I moved the single file into a folder. It now sees the chapters, but the bookmarks are gone again!  (Just spend a while recreating the bookmarks based on the text dump.)

**Comment by strider72** [comment] 2022-08-16 14:58
Notably, a different audiobook does show chapters even though it's still a bare file in the book folder

**Comment by PaulWoitaschek** [comment] 2022-08-26 21:31
I think this is a duplicate of https://github.com/PaulWoitaschek/Voice/issues/1429 and should be fixed in 6.0.9

**Closed by PaulWoitaschek** 2022-08-26 21:31 UTC
