### ISSUE TITLE
m4b no longer supported?

### ISSUE THREAD

**Issue by r3times** [PaulWoitaschek/Voice#1446] opened 2022-08-13 04:27 UTC
### What happened?

Having updated to 6.0.7 via F-Droid, I can no longer see nor play any m4b books. Whether a single file book, or multiple m4b files in their own sub-folder, Voice no longer finds them as before. Is this expected or by design?

mp3 books work as before, I'm using Android 8.1.0.

### Version

6.0.7

**Comment by PaulWoitaschek** [comment] 2022-08-13 05:53
Thank you for the report. This is a duplicate of #1429 and fixed in 6.0.9. 
I posted a comment here, asking why it does not appear on fdroid:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11501#note_1060489619

**Closed by PaulWoitaschek** 2022-08-13 05:53 UTC

**Comment by r3times** [comment] 2022-08-13 10:48
My apologies for not looking carefully before finding your recent discussions and solution about the m4b issue, Paul. I've now downloaded 6.0.9 from GitHub and can confirm that Voice is again working as beautifully as before.

Thanks so much for your efforts in this and Voice in general.
