### ISSUE TITLE
App freezes after pushing play

### ISSUE THREAD

**Issue by outcastkid** [PaulWoitaschek/Voice#947] opened 2020-03-03 09:10 UTC
The App freezes after pushing play(the track plays) or changing the track.

App-Version: 5.0.0-rc9 (Google Play Store)
Phone Name: Aquaris V
Android Version: 8.1.0

**Comment by PaulWoitaschek** [comment] 2020-03-04 12:03
I read it in the play store reviews and it seems to be device specific. It doesn't reproduce on my device so it would be great if someone could look into who has this issue.

**Comment by PaulWoitaschek** [comment] 2020-04-03 14:11
@outcastkid is this fixed in 5.0?

**Comment by outcastkid** [comment] 2020-04-03 14:40
It seems to be working again.

**Comment by PaulWoitaschek** [comment] 2020-04-03 20:12
Nice :)

**Closed by PaulWoitaschek** 2020-04-03 20:12 UTC
Labels: Bug, PR Welcome
