### ISSUE TITLE
[Bug] App's background service doesn't quit.

### ISSUE THREAD

**Issue by UsamaHaq** [PaulWoitaschek/Voice#974] opened 2020-04-11 18:48 UTC
Voice audio player doesn't exit.
I have to manually go to App Settings and "Force Stop" it.

This problem only started with current update.

App-Version: 5.0.1
Phone Name: Huawei Y7 Prime 2018 (LDN-L21)
Android Version: 8.0.0

**Comment by thw0rted** [comment] 2020-04-11 22:15
I think I'm seeing the same behavior? I play a book overnight, and when I wake up it's done, but the control notification is stuck in the tray.

Also, I have the Google "At a Glance" widget on my home screen, which shows the date, weather, and a selected notification that they decide is important. It's showing the title of the book I'm playing, but it started going crazy - the title would fade out like if the notification were dismissed, then fade in like it just started, over and over, a few times a second. Related?

**Comment by UsamaHaq** [comment] 2020-04-12 15:10
@thw0rted 
No, I am not seeing the same behavior, may be because I do not use the Google "At a Glance" widget.

The problem I am facing is that when I play an audiobook and pause it in the middle, and then close the application. The voice player keeps displaying in the Notification. I just doesn't goes away unless I "Force Stop" application from "App Settings".


--- I have only MX player running a video, But in notification both MX player and Voice AudioBook player are shown. Even though I closed Voice Audiobook player.

![Screenshot_20200412-200715](https://user-images.githubusercontent.com/3455826/79072262-93682b80-7cf9-11ea-8742-4f0951565ef2.jpg)

![Screenshot_20200412-200709](https://user-images.githubusercontent.com/3455826/79072250-76335d00-7cf9-11ea-8232-d50932e6b569.jpg)

**Comment by thw0rted** [comment] 2020-04-13 07:36
Sorry, to clarify, in addition to the widget thing, I'm also seeing the behavior you see. The notification sticks around and looks like a book is playing (shows a pause button), even though it's not.  I can't swipe to dismiss it because it thinks it's playing.  If I open Voice, play something, then pause it, the notification shows up as stopped (with a play button, not a pause button) and I can swipe to dismiss it.  But at some point later, it just comes back.

**Comment by UsamaHaq** [comment] 2020-04-16 01:23
@thw0rted 


> Sorry, to clarify, in addition to the widget thing, I'm also seeing the behavior you see. The notification sticks around and looks like a book is playing (shows a pause button), even though it's not. I can't swipe to dismiss it because it thinks it's playing. If I open Voice, play something, then pause it, the notification shows up as stopped (with a play button, not a pause button) and I can swipe to dismiss it. But at some point later, it just comes back.

Exactly the same problem.

**Comment by fnordson** [comment] 2020-04-16 14:08
I can confirm the same issue on Android 7.1.1

**Comment by heartofstone** [comment] 2020-04-20 19:44
I can confirm I am having the same issue on an samsung s9.

**Comment by Scorch-Mechanic** [comment] 2020-04-21 22:34
also having this problem

**Comment by wizard7926** [comment] 2020-04-30 22:51
Same problem here, Pixel 2 XL on Android 10.1 and app version 5.0.1

**Comment by HighElder** [comment] 2020-05-06 07:56
Similar problem with me. The icon disappears on my screen and notification bay, but the service seems to continue.

My problem: Sleep timer during the night + "Shake to reset" is set on.
In the previous version, "Shake to reset" was only active about 1 minute after the sleep timer, but in the current version 5.0.1 this background function continues to run permanently. Only hardquit does help.

Device: OnePlus 2, OxygenOS 3.6.1, Android 6.0.1

**Comment by HardyCheil** [comment] 2020-06-18 05:49
Seeing the same behaviour on Huawei EVA-L09 Android 7.0 EMUI 5.0.3

**Comment by wizard7926** [comment] 2020-06-27 18:17
It's been almost 3 months now since this was first reported, and the app hasn't been updated in 2 months. 

This is still happening and making me look for another app to use. 

Will this be fixed, @PaulWoitaschek?

**Comment by PaulWoitaschek** [comment] 2020-06-27 18:37
Yes it will eventually be fixed. But I don't have time currently so look for other apps to use if this is a blocker for your.

**Comment by wizard7926** [comment] 2020-06-27 18:40
> Yes it will eventually be fixed. But I don't have time currently so look for other apps to use if this is a blocker for your.

Thanks for the swift reply!

**Comment by hackbot1337** [comment] 2020-06-28 09:38
has anyone tried older versions? I might revert to a version before the UI change. maybe it will work.

**Comment by naitsirch** [comment] 2020-06-28 12:04
I had the same problem. But after the update to the latest version (via f-droid) the issue disappeared. I did not change any settings. Don't know why it is working for me, now...

**Comment by fnordson** [comment] 2020-06-28 12:18
My issue transformed.  
I am sometimes able to swipe it away from the notification area, it does come back at some time though.  
If I than push play from there, the app will crash on the next file...its quite annoying.

**Comment by wizard7926** [comment] 2020-06-28 15:42
> I had the same problem. But after the update to the latest version (via f-droid) the issue disappeared. I did not change any settings. Don't know why it is working for me, now...

Version 5.0.2 looks like it was released on F-Droid but not on Play Store? Why didn't 5.0.2 make the Play Store? I tried to update mine and it didn't take.

**Comment by PapeCoding** [comment] 2021-09-23 22:13
Same problem here as well.

Tested on: LineageOS 18.1 (Android 11)

**Comment by PaulWoitaschek** [comment] 2023-05-13 13:59
This should be fixed with the latest versions.

**Closed by PaulWoitaschek** 2023-05-13 13:59 UTC
