### ISSUE TITLE
2.5x is too slow

### ISSUE THREAD

**Issue by 532910** [PaulWoitaschek/Voice#1025] opened 2020-09-27 19:17 UTC
Please add support for up to 4x playback speed.

**Comment by allanlaal** [comment] 2020-11-20 07:39
I agree, but this is a duplicate of #255

**Closed** 2020-11-20 09:30 UTC

**Comment by PaulWoitaschek** [comment] 2022-08-02 19:53
https://github.com/PaulWoitaschek/Voice/discussions/1334#discussioncomment-3310890

Implemented :)
